In [0]:
import sys
import numpy as np

In [2]:
array_Id = np.array([4.5,3])
type(array_Id)

numpy.ndarray

In [3]:
array_Id.ndim

1

In [4]:
array_Id.shape

(2,)

In [6]:
matriz = np.array([
    [1,2,3],
    [4,5,6]
])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
matriz.ndim

2

In [8]:
matriz.shape

(2, 3)

In [9]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
np.ones((2))

array([1., 1.])

In [11]:
np.eye(3)
#matriz de identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.random.random((2,3))

array([[0.4743478 , 0.46510677, 0.33702703],
       [0.90127604, 0.73586155, 0.04586036]])

In [15]:
!cat np_text.txt
#leer un texto dentro del directorio

cat: sample_data: Is a directory


In [14]:
!ls
#mostrar lo que está dentro del directorio

sample_data


In [0]:
lista_2d=[[1,2,3],[4,5,6]]
array_2d=np.array([[1,2,3],[4,5,6]])

In [18]:
sys.getsizeof(lista_2d)

80

In [19]:
sys.getsizeof(array_2d)

160

In [0]:
big_lista = list(range(1000000))
big_array = np.array(range(1000000))

In [21]:
sys.getsizeof(big_lista)

9000112

In [22]:
sys.getsizeof(big_array)

8000096

In [24]:
%%timeit
#Benchmark del tiempo requerido
np.sum(np.arange(1000000))

100 loops, best of 3: 2.66 ms per loop


In [25]:
%%timeit
sum(range(1000000))

10 loops, best of 3: 16.8 ms per loop


In [26]:
np.array([1.0,5.4], dtype=int).dtype

dtype('int64')

In [27]:
np.array([1.0,2.0,"patata"])

array(['1.0', '2.0', 'patata'], dtype='<U32')

In [28]:
%%timeit
["{}".format(i) for i in range(1000000)]

1 loop, best of 3: 331 ms per loop


In [0]:
f = np.vectorize(lambda x: "{}".format(x))

In [30]:
%%timeit
f(np.arange(100000))

10 loops, best of 3: 56.8 ms per loop


In [40]:
matriz_34 = np.array([
    [1,2,3,4], [5,6,7,8], [9,10,11,12]
])
matriz_34

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
matriz_34[0]

array([1, 2, 3, 4])

In [42]:
matriz_34[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [43]:
matriz_34[:,1]

array([ 2,  6, 10])

In [44]:
matriz_34[1,1]

6

In [45]:
seleccion = matriz_34[1,3]
print(seleccion)
seleccion=100
matriz_34

8


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
seccion = matriz_34[:2]
seccion

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [47]:
seccion[0,0] = 100
matriz_34

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [48]:
matriz_32 = np.array([
    [1,4], [2,4], [5,0]
])
matriz_32

array([[1, 4],
       [2, 4],
       [5, 0]])

In [49]:
indice_filtrado = matriz_32 >=2
indice_filtrado

array([[False,  True],
       [ True,  True],
       [ True, False]])

In [50]:
matriz_32[indice_filtrado]

array([4, 2, 4, 5])

In [0]:
array1 = np.array([[1,2], [3,4]])

In [0]:
array2 = np.array([[23,5],[3,0]])

In [53]:
array1 + array2

array([[24,  7],
       [ 6,  4]])

In [55]:
array1 * array2

array([[23, 10],
       [ 9,  0]])

In [57]:
array1 @ array2
#Multiplicación de matrices

array([[29,  5],
       [81, 15]])

In [58]:
array1.dot(array2)

array([[29,  5],
       [81, 15]])

# Ejercicios
https://github.com/manugarri/curso_data_science/tree/master/Secciones/Seccion3.Intro_a_Data_Science/Intro_a_Numpy_ejercicios

crea un numpy array que tenga la siguente estructura

[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
llamalo array

In [76]:
array = np.array([
    [1, 6, 11], 
    [2, 7, 12], 
    [3, 8, 13], 
    [4, 9, 14], 
    [5, 10, 15]])
array.shape

(5, 3)

In [77]:
array[:,1]

array([ 6,  7,  8,  9, 10])

In [78]:
array2b = np.arange(15,56)
array2b

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

In [79]:
array2b[4] = 23
array2b

array([15, 16, 17, 18, 23, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

In [80]:
array2b[::-1]

array([55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39,
       38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22,
       21, 20, 23, 18, 17, 16, 15])

In [86]:
#Crea una matriz diagonal donde los elementos de la diagonal sean los 5 
#primeros valores pares de array2, llamala matriz_diag pista: usa np.diag

matriz_diag = np.diag([i for i in array2b if not i%2][0:5])
matriz_diag

array([[16,  0,  0,  0,  0],
       [ 0, 18,  0,  0,  0],
       [ 0,  0, 20,  0,  0],
       [ 0,  0,  0, 22,  0],
       [ 0,  0,  0,  0, 24]])

In [88]:
matriz_diag.ndim

2

In [96]:
matrizA = np.random.random((5,3))
matriz_diag @ matrizA

array([[ 4.82724022,  2.08734553,  9.36597472],
       [ 1.8266147 ,  0.64823243,  8.23071847],
       [12.17043482,  5.81117835, 18.2389851 ],
       [10.19796004,  4.478201  ,  5.01271874],
       [16.5816449 , 18.29383491,  3.20470193]])