# Regresión lineal con scikit-learn

In [0]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import pandas as pd
import numpy as np

In [0]:
data = pd.read_csv("https://raw.githubusercontent.com/joanby/python-ml-course/master/datasets/ads/Advertising.csv")

In [0]:
feature_cols = ["TV", "Radio", "Newspaper"]

In [0]:
X = data[feature_cols]
Y = data["Sales"]
#Y es la variable a predecir.

In [0]:
estimator = SVR(kernel="linear")
selector = RFE(estimator, 2, step=1) #Recursive feature elimination.
#Me quiero quedar con dos variables y que lo haga en un paso.
selector = selector.fit(X,Y)

Información y parámetros del SVR https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVR.html

In [0]:
selector.support_
#Descarta "Newspaper".

array([ True,  True, False])

In [0]:
selector.ranking_
#A menor número, más representativa/significativa.

array([1, 1, 2])

In [0]:
#Hacer un modelo lineal con scikit
from sklearn.linear_model import LinearRegression

In [0]:
X_pred = X[["TV", "Radio"]]

In [0]:
lm = LinearRegression()
lm.fit(X_pred, Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [0]:
lm.intercept_

2.921099912405138

In [0]:
lm.coef_

array([0.04575482, 0.18799423])

In [0]:
lm.score(X_pred,Y)

0.8971942610828956